"""
Models for the Bi-Weekly Evidence Log system.

WeeklyLog       — one row per (application_id, week_number) pair
Artifact        — one photo per check-in (Wednesday or Saturday)
AIQuizAttempt   — one AI quiz per week, generated after Saturday submission
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Integer, String, Boolean, DateTime, ForeignKey, Enum, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

import enum


class CheckInType(str, enum.Enum):
    wednesday = "wednesday"
    saturday = "saturday"


class WeeklyLog(Base):
    """One entry per week per active placement."""

    __tablename__ = "weekly_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    application_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("applications.id", ondelete="CASCADE"), nullable=False
    )
    week_number: Mapped[int] = mapped_column(Integer, nullable=False)

    # Wednesday check-in content (focus_area, core_action, the_blocker, the_takeaway)
    wed_content: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # Saturday check-in content (same four fields)
    sat_content: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    wed_submitted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    sat_submitted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    artifacts: Mapped[list["Artifact"]] = relationship(
        "Artifact", back_populates="weekly_log", cascade="all, delete-orphan"
    )
    quiz_attempt: Mapped["AIQuizAttempt | None"] = relationship(
        "AIQuizAttempt", back_populates="weekly_log", uselist=False, cascade="all, delete-orphan"
    )


class Artifact(Base):
    """One photo artifact per check-in slot (Wed or Sat)."""

    __tablename__ = "artifacts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    weekly_log_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("weekly_logs.id", ondelete="CASCADE"), nullable=True
    )
    check_in_type: Mapped[CheckInType | None] = mapped_column(
        Enum(CheckInType, name="check_in_type_enum"), nullable=True
    )
    photo_url: Mapped[str] = mapped_column(String(500), nullable=False)
    # Server-generated West Africa Time timestamp for tamper-evidence
    server_timestamp_wat: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # "camera" is the only accepted upload source (no file picker)
    upload_source: Mapped[str | None] = mapped_column(String(20), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    weekly_log: Mapped["WeeklyLog"] = relationship("WeeklyLog", back_populates="artifacts")


class AIQuizAttempt(Base):
    """AI-generated quiz taken after the student submits Saturday's check-in."""

    __tablename__ = "ai_quiz_attempts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    weekly_log_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("weekly_logs.id", ondelete="CASCADE"), nullable=False, unique=True
    )

    # Generated by Gemini from that week's log content
    questions: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    student_answers: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    correct_answers: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    # Score out of 5; None until the student submits answers
    score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    # True if the student switched tabs / left window during the quiz
    failed_due_to_tab_switch: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false"
    )
    attempted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    weekly_log: Mapped["WeeklyLog"] = relationship(
        "WeeklyLog", back_populates="quiz_attempt"
    )
