"""Increase skill_name length in internship_requirements

Revision ID: 10bbda241d7c
Revises: c84704c0ca73
Create Date: 2026-09-24 12:57:09.847938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bbda241d7c'
down_revision: Union[str, None] = 'c84704c0ca73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('internship_requirements', 'skill_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_verification_submissions_company_tier_active'), table_name='verification_submissions', postgresql_where="((status)::text <> ALL ((ARRAY['approved'::character varying, 'rejected'::character varying])::text[]))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_verification_submissions_company_tier_active'), 'verification_submissions', ['company_id', 'tier'], unique=True, postgresql_where="((status)::text <> ALL ((ARRAY['approved'::character varying, 'rejected'::character varying])::text[]))")
    op.alter_column('internship_requirements', 'skill_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
