"""Add industry supervisor and weekly pulse models

Revision ID: 1a2b3c4d5e6f
Revises: 9ed027b4dec4
Create Date: 2026-06-22 22:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = '9ed027b4dec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_supervisor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weekly_pulse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('micro_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pin_links', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('hit_miss', sa.Boolean(), nullable=True),
    sa.Column('reflection', sa.String(length=200), nullable=True),
    sa.Column('supervisor_endorsements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_pulse')
    op.drop_table('industry_supervisor_profiles')
    # ### end Alembic commands ###
