"""add coursework to job families

Revision ID: 2249789b93b7
Revises: 69a1f4d074af
Create Date: 2026-09-15 07:33:44.222510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2249789b93b7'
down_revision: Union[str, None] = '69a1f4d074af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_families', sa.Column('coursework_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_families', 'coursework_options')
    # ### end Alembic commands ###
