"""add_activation_token_and_is_activated_to_users

Revision ID: 2f0f2d8b3ca4
Revises: 44ab20a036ce
Create Date: 2026-09-15 06:12:06.360744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0f2d8b3ca4'
down_revision: Union[str, None] = '44ab20a036ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_users_activation_token'), 'users', ['activation_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_activation_token'), table_name='users')
    op.drop_column('users', 'is_activated')
    op.drop_column('users', 'activation_token')
    # ### end Alembic commands ###
