"""add_rejection_note_and_is_active

Revision ID: 44ab20a036ce
Revises: c8a73930b24d
Create Date: 2026-07-13 13:04:57.569742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ab20a036ce'
down_revision: Union[str, None] = 'c8a73930b24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rejection_note', sa.String(length=500), nullable=True))
    op.add_column('head_of_departments', sa.Column('rejection_note', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('head_of_departments', 'rejection_note')
    op.drop_column('companies', 'rejection_note')
    # ### end Alembic commands ###
