"""add revision count and comment history

Revision ID: 596360dcd3fd
Revises: dc8937719771
Create Date: 2026-06-24 15:27:15.957354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '596360dcd3fd'
down_revision: Union[str, None] = 'dc8937719771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unified_frameworks', sa.Column('revision_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('unified_frameworks', sa.Column('comment_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unified_frameworks', 'comment_history')
    op.drop_column('unified_frameworks', 'revision_count')
    # ### end Alembic commands ###
