"""add_id_document_url_to_hod

Revision ID: 69a1f4d074af
Revises: 2f0f2d8b3ca4
Create Date: 2026-09-15 06:30:09.184998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a1f4d074af'
down_revision: Union[str, None] = '2f0f2d8b3ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('head_of_departments', sa.Column('id_document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('head_of_departments', 'id_document_url')
    # ### end Alembic commands ###
