"""Add company_cycle_entitlements and student counts

Revision ID: 9ed027b4dec4
Revises: befbfbde415a
Create Date: 2026-06-21 18:55:21.180981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed027b4dec4'
down_revision: Union[str, None] = 'befbfbde415a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_cycle_entitlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('total_slots_offered', sa.Integer(), nullable=True),
    sa.Column('equity_quota_required', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('equity_quota_met', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fair_participation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['internship_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('project_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('students', sa.Column('coursework_count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'coursework_count')
    op.drop_column('students', 'project_count')
    op.drop_table('company_cycle_entitlements')
    # ### end Alembic commands ###
