"""Phase 2 models

Revision ID: befbfbde415a
Revises: 002
Create Date: 2026-06-20 15:35:28.821300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'befbfbde415a'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_admin_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('previous_fair_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('company_logo_url', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('intern_satisfaction_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('full_time_offer_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('internships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('stipend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('job_family_id', sa.Integer(), nullable=True),
    sa.Column('sub_role_id', sa.Integer(), nullable=True),
    sa.Column('track_type', sa.String(length=20), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=True),
    sa.Column('accepted_tiers', postgresql.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sub_role_id'], ['sub_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('fit_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tier_at_application', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('industry_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('academic_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_supervisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['industry_supervisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internship_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_sub_roles_job_family_id'), table_name='sub_roles')
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_sub_roles_job_family_id'), 'sub_roles', ['job_family_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    op.drop_table('internship_requirements')
    op.drop_table('applications')
    op.drop_table('internships')
    op.drop_table('companies')
    op.drop_table('internship_cycles')
    # ### end Alembic commands ###
