"""add_profile_fields_to_industry_supervisor

Revision ID: c8a73930b24d
Revises: 41d79fd44587
Create Date: 2026-07-12 18:05:32.008642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a73930b24d'
down_revision: Union[str, None] = '41d79fd44587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry_supervisor_profiles', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('industry_supervisor_profiles', sa.Column('linkedin_profile', sa.String(length=255), nullable=True))
    op.add_column('industry_supervisor_profiles', sa.Column('mentorship_philosophy', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industry_supervisor_profiles', 'mentorship_philosophy')
    op.drop_column('industry_supervisor_profiles', 'linkedin_profile')
    op.drop_column('industry_supervisor_profiles', 'phone_number')
    # ### end Alembic commands ###
