"""Add phone and office location to HOD

Revision ID: de2a49f9afb0
Revises: ea0a6b19b9c3
Create Date: 2026-07-11 16:44:11.236065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2a49f9afb0'
down_revision: Union[str, None] = 'ea0a6b19b9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('head_of_departments', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('head_of_departments', sa.Column('office_location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('head_of_departments', 'office_location')
    op.drop_column('head_of_departments', 'phone_number')
    # ### end Alembic commands ###
