"""add_skill_verification_tables_and_columns

Revision ID: ea0a6b19b9c3
Revises: b2c3d4e5f6a7
Create Date: 2026-07-06 14:57:11.608532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea0a6b19b9c3'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_verification_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('difficulty_tier', sa.String(length=50), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_snapshot_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_verification_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('failed_due_to_tab_switch', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('questions_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('student_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questions_snapshot_id'], ['skill_verification_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_ai_quiz_attempts_id'), table_name='ai_quiz_attempts')
    op.alter_column('artifacts', 'check_in_type',
               existing_type=postgresql.ENUM('wednesday', 'saturday', name='check_in_type_enum'),
               nullable=True)
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_monthly_endorsements_app_month'), table_name='monthly_endorsements')
    op.drop_index(op.f('ix_monthly_endorsements_id'), table_name='monthly_endorsements')
    op.add_column('student_skills', sa.Column('verification_status', sa.String(length=20), server_default='unverified', nullable=False))
    op.add_column('student_skills', sa.Column('successful_reverify_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('student_skills', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student_skills', sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('students', sa.Column('verified_fit_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('students', sa.Column('skill_verification_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_weekly_logs_application_week'), table_name='weekly_logs')
    op.drop_index(op.f('ix_weekly_logs_id'), table_name='weekly_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weekly_logs_id'), 'weekly_logs', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_logs_application_week'), 'weekly_logs', ['application_id', 'week_number'], unique=True)
    op.drop_column('students', 'skill_verification_completed_at')
    op.drop_column('students', 'verified_fit_score')
    op.drop_column('student_skills', 'cooldown_until')
    op.drop_column('student_skills', 'last_attempt_at')
    op.drop_column('student_skills', 'successful_reverify_count')
    op.drop_column('student_skills', 'verification_status')
    op.create_index(op.f('ix_monthly_endorsements_id'), 'monthly_endorsements', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_endorsements_app_month'), 'monthly_endorsements', ['application_id', 'month_year'], unique=True)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.alter_column('artifacts', 'check_in_type',
               existing_type=postgresql.ENUM('wednesday', 'saturday', name='check_in_type_enum'),
               nullable=False)
    op.create_index(op.f('ix_ai_quiz_attempts_id'), 'ai_quiz_attempts', ['id'], unique=False)
    op.drop_table('skill_verification_attempts')
    op.drop_table('skill_verification_questions')
    # ### end Alembic commands ###
